version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mcccnc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MccAdmin
    volumes:
      - postgres_data:/var/lib/postgresql # Korrigiertes Volume-Mapping

  redis:
    image: "redis:alpine"

  web:
    build: .
    command: gunicorn dashboard.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /home/heinz/Dokumente/megacell/test:/data
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:MccAdmin@db:5432/mcccnc  # Hostname auf "db" ge채ndert
      - REDIS_URL=redis://redis:6379/0  # Hostname auf "redis" ge채ndert
    cap_add:
      - NET_ADMIN

  celeryworker:
    build: .
    command: celery -A dashboard worker --loglevel=info
    volumes:
      - .:/app
      - /home/heinz/Dokumente/megacell/test:/data
    depends_on:
      - db
      - redis
    environment: # Umgebungsvariablen hinzugef체gt
      - DATABASE_URL=postgres://postgres:MccAdmin@db:5432/mcccnc
      - REDIS_URL=redis://redis:6379/0

  celerybeat:
    build: .
    command: celery -A dashboard beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
      - /home/heinz/Dokumente/megacell/test:/data
    depends_on:
      - db
      - redis
    environment: # Umgebungsvariablen hinzugef체gt
      - DATABASE_URL=postgres://postgres:MccAdmin@db:5432/mcccnc
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:

